### ISSUE TITLE
Wie device in FHEM definieren?

### ISSUE THREAD

**Issue by reibuehl** [Quantum1337/32_SiSi.pm#1]
Sollte in der Readme.md/Dokumentation nicht irgendwo beschrieben sein, wie man das Device in FHEM anlegt? Ist zwar nur ein "define <name> SiSi, aber da das Modul ja auch keine commandref Sektion anlegt wäre das schon schön. Besser wäre natürlich eine commandref Sektion ;-)

**Comment by Quantum1337** [comment]
Commandref wurde hinzugefügt.
